In [ ]:
!pip install streamlit plotly

In [2]:
import pandas as pd

data = {
    "type": [
        "Movie","Movie","TV Show","Movie","TV Show",
        "Movie","Movie","TV Show","Movie","TV Show"
    ],
    "title": [
        "Red Notice","Extraction","Wednesday","Bird Box","Stranger Things",
        "The Irishman","Army of the Dead","Money Heist","Enola Holmes","Dark"
    ],
    "country": [
        "United States","United States","United States","United States","United States",
        "United States","United States","Spain","United Kingdom","Germany"
    ],
    "release_year": [
        2021,2020,2022,2018,2019,
        2019,2021,2020,2020,2017
    ],
    "rating": [
        "PG-13","R","TV-14","R","TV-14",
        "R","R","TV-MA","PG-13","TV-MA"
    ],
    "listed_in": [
        "Action","Action","Comedy",
        "Drama","Drama",
        "Crime","Action",
        "Crime","Adventure","Drama"
    ]
}

df = pd.DataFrame(data)

df.to_csv("netflix.csv", index=False)

print("netflix.csv created successfully!")
df.head()

netflix.csv created successfully!

      type            title        country  release_year rating listed_in
0    Movie       Red Notice  United States          2021  PG-13    Action
1    Movie       Extraction  United States          2020      R    Action
2  TV Show        Wednesday  United States          2022  TV-14    Comedy
3    Movie         Bird Box  United States          2018      R     Drama
4  TV Show  Stranger Things  United States          2019  TV-14     Drama

In [ ]:
import pandas as pd

df = pd.read_csv("netflix.csv")

df.head()

      type            title        country  release_year rating listed_in
0    Movie       Red Notice  United States          2021  PG-13    Action
1    Movie       Extraction  United States          2020      R    Action
2  TV Show        Wednesday  United States          2022  TV-14    Comedy
3    Movie         Bird Box  United States          2018      R     Drama
4  TV Show  Stranger Things  United States          2019  TV-14     Drama

In [4]:
%%writefile app.py

import streamlit as st
import pandas as pd
import plotly.express as px

# -------------------------
# Load Dataset
# -------------------------
df = pd.read_csv("netflix.csv")

st.title("🎬 Netflix Data Storytelling App")

# -------------------------
# Dataset Introduction
# -------------------------
st.header("📖 Dataset Introduction")

movies = len(df[df["type"] == "Movie"])
tvshows = len(df[df["type"] == "TV Show"])

countries = df["country"].dropna().nunique()

col1, col2, col3 = st.columns(3)

col1.metric("Movies", movies)
col2.metric("TV Shows", tvshows)
col3.metric("Countries", countries)

# -------------------------
# EDA
# -------------------------
st.header("📊 Exploratory Data Analysis")

# Content by Year
df["release_year"] = pd.to_numeric(df["release_year"], errors="coerce")

year_count = df["release_year"].value_counts().sort_index()

st.subheader("Content by Release Year")

fig1 = px.line(
    x=year_count.index,
    y=year_count.values,
    labels={"x":"Year","y":"Count"}
)

st.plotly_chart(fig1)

# Top Countries

st.subheader("Top Countries")

country_count = (
    df["country"]
    .dropna()
    .str.split(", ")
    .explode()
    .value_counts()
    .head(10)
)

fig2 = px.bar(
    x=country_count.index,
    y=country_count.values,
    labels={"x":"Country","y":"Titles"}
)

st.plotly_chart(fig2)

# Top Genres

st.subheader("Top Genres")

genre_count = (
    df["listed_in"]
    .str.split(", ")
    .explode()
    .value_counts()
    .head(10)
)

fig3 = px.bar(
    x=genre_count.index,
    y=genre_count.values,
    labels={"x":"Genre","y":"Count"}
)

st.plotly_chart(fig3)

# Rating Distribution

st.subheader("Ratings Distribution")

rating_count = df["rating"].value_counts()

fig4 = px.pie(
    values=rating_count.values,
    names=rating_count.index
)

st.plotly_chart(fig4)

# Movies vs TV Shows

st.subheader("Movies vs TV Shows")

type_count = df["type"].value_counts()

fig5 = px.pie(
    values=type_count.values,
    names=type_count.index
)

st.plotly_chart(fig5)

# -------------------------
# Insights
# -------------------------

st.header("🔍 Key Insights")

st.write("• Most content comes from the USA.")
st.write("• Netflix content increased rapidly after 2015.")
st.write("• Drama is one of the most common genres.")
st.write("• Movies significantly outnumber TV Shows.")
st.write("• Content production has grown steadily over time.")

# -------------------------
# Recommendations
# -------------------------

st.header("💡 Recommendations")

st.write("• Increase regional language content.")
st.write("• Expand underrepresented genres.")
st.write("• Invest more in emerging markets.")
st.write("• Create more original TV Shows.")

Writing app.py

In [5]:
!ls

app.py	netflix.csv  sample_data

In [7]:
!streamlit run app.py &>/content/logs.txt &

In [8]:
!curl https://loca.lt/mytunnelpassword

34.169.82.126

In [ ]:
!npx localtunnel --port 8501

⠙⠹⠸⠼⠴⠦Need to install the following packages:
localtunnel@2.0.2
Ok to proceed? (y) y

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸your url is: https://whole-ways-fetch.loca.lt